### ISSUE TITLE
Constant 1% CPU usage

### ISSUE THREAD

**Issue by riegaz** [TheDen/galvani#5]
Hi,

I know it is not the world but your app consumes 1% of my macbook air M2 CPU. Indeed, this is not much but having 20 small apps installed adds up. Other apps like Bartender only consume 0.1%.

I was wondering if there is something that can be done about it. If you know why, maybe it is worthwhile thinking about a solution.

What do you think?

**Comment by TheDen** [comment]
Hey @riegaz, thanks for the raising this issue, I appreciate your feedback on the CPU usage!

We've cut a new [release](https://github.com/TheDen/galvani/releases/tag/0.2.0) — @BradLewis made some improvements in https://github.com/TheDen/galvani/pull/6 that directly address your issue with CPU usage. Galvani should prompt for an update, and after restarting the app, check if you have version `0.2.0`— it should hopefully consume less CPU  time.

**Comment by riegaz** [comment]
Thanks. That seems to do the trick as I don't see it within the apps consuming 1% at any time. Great! I guess we can close this issue. Rapid solution :)

**Comment by TheDen** [comment]
No worries @riegaz! We pushed one more release after a hotfix by @BradLewis (https://github.com/TheDen/galvani/pull/7) https://github.com/TheDen/galvani/releases/tag/0.2.1

Please update to version `0.2.1` and it should all be good! :)

I'll close this issue, thanks again for raising this
